sudo: required

language: ruby

services:
  - docker

env:
  - TARGET_CONTAINER_ID=container-crontab

before_script:
  - docker build -t crontab .
  - docker run -d --name $TARGET_CONTAINER_ID crontab

script:
  - bundle exec rspec
