sudo: required

language: ruby

services:
  - docker

env:
  - TARGET_CONTAINER_ID=container-crontab

before_script:
  - docker build -t quay.io/wantedly/crontab-docker:latest .

script:
  - bundle exec rake spec
